added ltl2ba

diff --git a/bymc/cegar b/bymc/cegar
--- a/bymc/cegar
+++ b/bymc/cegar
@@ -14,6 +14,7 @@ PROP=$2
 BYMC_HOME=`dirname $0`
 
 SPIN=spin
+LTL2BA="$BYMC_HOME/../deps/ltl2ba-1.1/ltl2ba"
 PANCC_FLAGS=${PANCC_FLAGS:-"-DVECTORSZ=2048 -DCOLLAPSE -DSC"}
 PAN_FLAGS=${PAN_FLAGS:-"-m100000"}
 SPIN_OUT="spin.out"
@@ -21,6 +22,12 @@ cmd=""
 step="0"
 rand=""
 out=""
+
+if [ ! -x "$LTL2BA" ]; then
+    echo "WARNING: $LTL2BA is not found. Please go to `dirname $LTLBA` and invoke make."
+    echo "Using 'spin -f' instead of ltl2ba. It may slow down the performance."
+    exit 1
+fi
 
 CUR_DIR=`pwd`
 cd $BYMC_HOME
@@ -42,10 +49,13 @@ fi
 rm -rf $SPIN_OUT spin.trace refinement.out
 
 while [ "$cmd" != "q" ]; do
-    $SPIN -f "!`head $PROP.ltl`" >$PROP.never || (cat $PROP.never; exit 1)
-    $SPIN -a -N $PROP.never abs-counter.prm \
-        && gcc $rand $PANCC_FLAGS -o ./pan pan.c \
-        && ./pan $PAN_FLAGS -a 2>&1 | tee $SPIN_OUT
+    echo "Converting the spec: !`head $PROP.ltl`..."
+    #$SPIN -f "!`head $PROP.ltl`" >$PROP.never || (cat $PROP.never; exit 1)
+    $LTL2BA -f "!`head $PROP.ltl`" >$PROP.never || (cat $PROP.never; exit 1)
+    echo "Generating pan..."
+    $SPIN -a -N $PROP.never abs-counter.prm || exit 2
+    (gcc $rand $PANCC_FLAGS -o ./pan pan.c \
+        && ./pan $PAN_FLAGS -a 2>&1 | tee $SPIN_OUT) || exit 3
 
     if egrep -q "errors: +0" $SPIN_OUT; then
         echo "The property is verified in $step refinement steps"
