added safety

diff --git a/bymc/run-concrete b/bymc/run-concrete
--- a/bymc/run-concrete
+++ b/bymc/run-concrete
@@ -24,12 +24,15 @@ BYMC_HOME=`cd $BYMC_HOME; pwd`
 PROG_S=`basename $PROG .pml`
 
 SPIN=${SPIN:-spin}
-PANCC_FLAGS=${PANCC_FLAGS:-"-DVECTORSZ=2048 -DCOLLAPSE -DSC -DNOREDUCE"}
+PANCC_FLAGS=${PANCC_FLAGS:-"-DCOLLAPSE -DSC -DNOREDUCE"}
 PAN_FLAGS=${PAN_FLAGS:-"-m100000"} #-m50000000"
 cmd=""
 step="0"
 rand=""
 out=""
+if [ "$PROP" == "safety" ]; then
+    PANCC_FLAGS="$PANCC_FLAGS -DSAFETY"
+fi
 
 CUR_DIR=`pwd`; CUR_DIR=`cd $CUR_DIR; pwd`
 cd $BYMC_HOME
@@ -64,16 +67,24 @@ cat >>"$SCRIPT" <<EOF
 echo "Changed directory to $INSTANCE"
 cd "$INSTANCE"
 
-$SPIN -f "!\`head $PROP.ltl\`" >$PROP.never || (cat $PROP.never; exit 1)
-# turn on the old scoping rules, otherwise remote references do not work
-$SPIN -O -a -N $PROP.never concrete.prm || (echo "FAILED spin -a"; exit 1)
+if [ "$PROP" != "safety" ]; then
+  $SPIN -f "!\`head $PROP.ltl\`" >$PROP.never || (cat $PROP.never; exit 1)
+  # turn on the old scoping rules, otherwise remote references do not work
+  $SPIN -O -a -N $PROP.never concrete.prm || (echo "FAILED spin -a"; exit 1)
+else
+  $SPIN -O -a concrete.prm || (echo "FAILED spin -a"; exit 1)
+fi
 
 START_TIME=\$(date +%s)
 
 echo "+ gcc $rand $PANCC_FLAGS -o ./pan pan.c"
 echo "+ ./pan $PAN_FLAGS -a 2>&1 | tee $SPIN_OUT"
-gcc $rand $PANCC_FLAGS -o ./pan pan.c \
-  && ./pan $PAN_FLAGS -a 2>&1 | tee $SPIN_OUT
+gcc $rand $PANCC_FLAGS -o ./pan pan.c || (echo "gcc failed"; exit 3)
+if [ "$PROP" != "safety" ]; then
+  ./pan $PAN_FLAGS -a 2>&1 | tee $SPIN_OUT
+else
+  ./pan $PAN_FLAGS 2>&1 | tee $SPIN_OUT
+fi
 
 if egrep -q "errors: +0" $SPIN_OUT; then
     out="|00:exitcode=ok|01:valid=yes"
