parameters

diff --git a/bymc/verifypa-nusmv-bmc b/bymc/verifypa-nusmv-bmc
--- a/bymc/verifypa-nusmv-bmc
+++ b/bymc/verifypa-nusmv-bmc
@@ -1,4 +1,25 @@
 #!/bin/bash
+#
+# Run the abstraction refinement loop with nusmv in bmc mode
 
-TARGET_MC=nusmv `dirname $0`/cegar $@
+DEPTH=10
+NUSMV_VERBOSE=0
+
+# parse options
+TEMPOPTS=`getopt -o d:w --long depth:nusmv-verbose: -n '$@' -- "$@"`
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+
+eval set -- "$TEMPOPTS"
+while true ; do
+    case "$1" in
+    -d|--depth) DEPTH=$2 ; shift 2 ;;
+    -w|--nusmv-verbose) NUSMV_VERBOSE=$2 ; shift 2 ;;
+    --) shift ; break ;;
+    *) echo "Internal error!" ; exit 1 ;;
+    esac
+done
+
+# run the tool
+DEPTH=$DEPTH NUSMV_VERBOSE=$NUSMV_VERBOSE TARGET_MC=nusmv \
+    `dirname $0`/cegar "$@"
 
