update help and readme

diff --git a/bymc/verifypa-nusmv-bdd b/bymc/verifypa-nusmv-bdd
--- a/bymc/verifypa-nusmv-bdd
+++ b/bymc/verifypa-nusmv-bdd
@@ -11,12 +11,26 @@ NO_JUSTICE=""
 SOURCE=""
 
 # parse options
-TEMPOPTS=`POSIXLY_CORRECT=1 getopt -o w: --long nusmv-verbose:,rel-mono,rel-reach,no-justice,source:,limit-time:,limit-mem: -n '$@' -- "$@"`
+TEMPOPTS=`POSIXLY_CORRECT=1 getopt -o h,w: --long help,nusmv-verbose:,rel-mono,rel-reach,no-justice,source:,limit-time:,limit-mem: -n '$@' -- "$@"`
 if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+
+function help_and_quit() {
+    echo "use $0 <switches> prog spec <bymc_switches>"
+    echo " where the switches are"
+    echo "  -w|--nusmv-verbose <level>: set the verbosity level"
+    echo "  --rel-reach: compute reachable states first (in NuSMV)"
+    echo "  --rel-mono: monolithic transition relation (in NuSMV)"
+    echo "  --source: execute the script in NuSMV"
+    echo "  --limit-time: limit (in seconds) cpu time of subprocesses (ulimit -t)"
+    echo "  --limit-mem: limit (in MB) virtual memory of subprocesses (ulimit -v)"
+    echo "  -h|--help: show this help message"
+    exit 1
+}
 
 eval set -- "$TEMPOPTS"
 while true ; do
     case "$1" in
+    -h|--help) help_and_quit ;;
     -w|--nusmv-verbose) NUSMV_VERBOSE=$2 ; shift 2 ;;
     --source) SOURCE=$2 ; shift 2 ;;
     --rel-mono) MONO="1" ; shift ;;
@@ -25,9 +39,14 @@ while true ; do
     --limit-time) TIME_LIMIT=$2 ; shift 2 ;;
     --limit-mem) MEM_LIMIT=$((1024*$2)) ; shift 2 ;;
     --) shift ; break ;;
-    *) echo "Internal error!" ; exit 1 ;;
+    *) echo "Internal error!" ;
+       help_and_quit;;
     esac
 done
+
+if [ "$#" -lt 2 ]; then
+    help_and_quit
+fi
 
 echo ulimit -SHv $MEM_LIMIT
 ulimit -SHv $MEM_LIMIT
